name: deploy-spec
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy Spec
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: index.bs
          DESTINATION: index.html
          TOOLCHAIN: bikeshed
          GH_PAGES_BRANCH: gh-pages
          BUILD_FAIL_ON: warning
